console.log(document.body.childNodes)
console.log(document.body.childNodes[0])
console.log(document.querySelector("ul").childNodes)
console.log(document.querySelector("ul").childNodes[1])
console.log(document.querySelector("ul").parentNode)
console.log(document.querySelector("nav").previousElementSibling)
console.log(document.querySelector("nav").firstChild)
console.log(document.querySelector("nav").firstElementChild)
console.log(document.querySelector("ul").children)
console.log(document.querySelector("nav").nextSibling)
console.log(document.querySelector("nav").nextElementSibling)
console.log(document.querySelector("ul").children[2])
// console.log(document.ELEMENT_NODE)
// console.log(document.ATTRIBUTE_NODE)
// console.log(document.TEXT_NODE)
// console.log(document.COMMENT_NODE)